/* Generated By:JJTree&JavaCC: Do not edit this line. SearchParserConstants.java */
package model.network.search.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SearchParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int LEFTPARENTHESIS = 7;
  /** RegularExpression Id. */
  int RIGHTPARENTHESIS = 8;
  /** RegularExpression Id. */
  int WORD_TOKEN = 9;
  /** RegularExpression Id. */
  int NUMBER_TOKEN = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"OR\"",
    "\"(\"",
    "\")\"",
    "<WORD_TOKEN>",
    "<NUMBER_TOKEN>",
  };

}
