/* Generated By:JavaCC: Do not edit this line. SearchParserTreeConstants.java Version 5.0 */
package model.network.search.parser;

public interface SearchParserTreeConstants
{
  public int JJTRECHERCHE = 0;
  public int JJTEXPRESSION = 1;
  public int JJTEXPRESSIONBIS = 2;
  public int JJTOPERATEUR = 3;
  public int JJTAND = 4;
  public int JJTOR = 5;
  public int JJTLEFTPARENTHESIS = 6;
  public int JJTRIGHTPARENTHESIS = 7;


  public String[] jjtNodeName = {
    "Recherche",
    "Expression",
    "ExpressionBis",
    "Operateur",
    "AND",
    "OR",
    "LEFTPARENTHESIS",
    "RIGHTPARENTHESIS",
  };
}
/* JavaCC - OriginalChecksum=30f56b5bd4e561c84f6ddb1ccb5fc333 (do not edit this line) */
